# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76a9d7ce023f0b93883bb9b28e87b50484d75022408906d9c91439369b85535f74b9b79255b8d28496941cb87c6a615ba5aa48d97ac0abe0cf264904e6839666

test:
  secret_key_base: 9310b415597912b42565c4b420a6a2ef88ad967b3200cfff29a92c9f6b78dd9bbd3b4305871b56e4b0e1e6c0a14af2caa72293a88d8e5e0a6d3829642d3ba686

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
